merge refs/heads/trunk into refs/heads/release

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,11 +1,24 @@
 #!/usr/bin/env sh
-
-# set -o pipefail
+#
+#
+# NOTE: Before you start yelling, yes this is NOT a GNU auto* build
+#       system. However, I have written this in a way that it
+#       has as few changes as needed.
+#
+#       You still have all the features:
+#
+#       - Cross Compilation Support
+#       - Support for various compilers and operating systems
+#       - Out-of-tree builds
+#       - DESTDIR/PREFIX install
+#       - Test suite
+#
+#       PLEASE READ THE README / HACKING GUIDE FOR MORE INFORMATION.
 
 CONFIGURE_CMD_ARGS="${*}"
 
-PACKAGE_VERSION="2.9.1"
-PACKAGE_DATE="04-Oct-2025"
+PACKAGE_VERSION="2.10.0"
+PACKAGE_DATE="31-Dec-2025"
 PACKAGE_STRING="gcli $PACKAGE_VERSION"
 PACKAGE_BUGREPORT="https://lists.sr.ht/~herrhotzenplotz/gcli-discuss"
 PACKAGE_URL="https://sr.ht/~herrhotzenplotz/gcli"
@@ -129,17 +142,17 @@ Configure build directory of gcli.
 
 OPTIONS:
     --prefix=PREFIX         Set installation prefix to PREFIX [DEFAULT: /usr/local]
-    --enable-libedit        Search and use libedit for interactive editing [DEFAULT: yes]
-    --disable-libedit       Do not use libedit
-    --enable-libreadline    Search and use libreadline for interactive editing [DEFAULT: yes]
-    --disable-libreadline   Disable use of libreadline
-    --enable-liblowdown     Search and use liblowdown for markdown rendering [DEFAULT: yes]
-    --disable-liblowdown    Disable use of liblowdown
+    --disable-libedit       Disable use of libedit for interactive editing [DEFAULT: autodetect]
+    --disable-libreadline   Disable use of libreadline for interactive editing [DEFAULT: autodetect]
+    --disable-liblowdown    Disable use of liblowdown for markdown rendering [DEFAULT: autodetect]
     --disable-librt         Forcefully disable linking librt [DEFAULT: no, except on Darwin]
     --enable-maintainer     Enable Maintainer Mode [DEFAULT: no]
                             You only want this if you're working on the gcli source code.
                             In this case certain build targets get enabled that only work
                             when the source directory is writable.
+                            Do NOT use this flag together with --release or when packaging
+                            gcli.
+    --enable-sanitisers     Enable compiler-specific sanitisers
     --debug                 Compile without optimisations, generate code with
                             debug information and enable additional compiler-specific
                             warnings and portability checks.
@@ -159,8 +172,8 @@ ENVIRONMENT:
     AR                      Archiver to use [DEFAULT: autodetect]
     RANLIB                  Ranlib to use [DEFAULT: autodetect]
     RM                      rm to use [DEFAULT: autodetect]
-    KYUA                    Path to Kyua [DEFAULT: autodetect]
     CCACHE                  Path to ccache [DEFAULT: autodetect]
+    PERL                    Path to perl for test suite [DEFAULT: autodetect]
     INSTALL                 Path to install [DEFAULT: autodetect]
     EXEEXT                  File extension of executable files for the host system [DEFAULT: '', '.exe' on Windows]
     OBJEXT                  File extension of object files for the host system [DEFAULT: '.o', '.obj' on Windows]
@@ -181,6 +194,8 @@ ENABLE_LIBREADLINE=1
 ENABLE_LIBLOWDOWN=1
 ENABLE_LIBRT=1
 ENABLE_MAINTAINER=${ENABLE_MAINTAINER:-0}
+ENABLE_TESTS=1
+ENABLE_SANITISERS=${ENABLE_SANITISERS:-0}
 
 # Parse flags
 while [ $# -gt 0 ]; do
@@ -193,24 +208,16 @@ while [ $# -gt 0 ]; do
 			PREFIX=${2}
 			shift; shift
 			;;
-		--enable-libedit)
-			ENABLE_LIBEDIT=1
+		--enable-libedit|--enable-libreadline|--enable-liblowdown)
+			echo "configure: warning: $1 is deprecated and ignored" >&2
 			shift
 			;;
 		--disable-libedit)
 			ENABLE_LIBEDIT=0
 			shift
 			;;
-		--enable-libreadline)
-			ENABLE_LIBREADLINE=1
-			shift
-			;;
 		--disable-libreadline)
 			ENABLE_LIBREADLINE=0
-			shift
-			;;
-		--enable-liblowdown)
-			ENABLE_LIBLOWDOWN=1
 			shift
 			;;
 		--disable-librt)
@@ -223,6 +230,14 @@ while [ $# -gt 0 ]; do
 			;;
 		--enable-maintainer)
 			ENABLE_MAINTAINER=1
+			shift
+			;;
+		--disable-tests)
+			ENABLE_TESTS=0
+			shift
+			;;
+		--enable-sanitisers)
+			ENABLE_SANITISERS=1
 			shift
 			;;
 		--debug)
@@ -289,7 +304,6 @@ PKG_CONFIG=${PKG_CONFIG:-$(find_program pkg-config pkg-config pkgconf)}
 [ $? -eq 0 ] || die "error: need pkg-config or pkgconf"
 
 find_package libcurl LIBCURL required
-find_package atf-c LIBATFC optional
 find_package libcrypto LIBCRYPTO required
 
 # Look for libedit if not disabled
@@ -385,15 +399,23 @@ LIBEXT_FOR_BUILD=${LIBEXT_FOR_BUILD:-$(guess_extension LIB $BUILD)} || die "erro
 AR=${AR:-ar}
 RANLIB=${RANLIB:-ranlib}
 RM=${RM:-rm}
-KYUA=${KYUA:-$(find_program kyua kyua)}
 CCACHE=${CCACHE:-$(find_program ccache ccache)}
 INSTALL=${INSTALL:-$(find_program install install ginstall)}
-SHELL=${SHELL:-$(find_program sh sh zsh bash)}
 [ $? -eq 0 ] || die "error: need install program"
+SHELL=${SHELL:-$(find_program sh sh zsh bash)}
 
 # If maintainer mode is enabled, we need lowdown(1)
 if [ ${ENABLE_MAINTAINER} -eq 1 ]; then
 	LOWDOWN=${LOWDOWN:-$(find_program lowdown lowdown)}
+	[ $? -eq 0 ] || die "error: couldn't find lowdown which is required in maintainer mode"
+fi
+
+if [ ${ENABLE_TESTS} -eq 1 ]; then
+	PERL=${PERL:-$(find_program perl perl perl5)}
+	if ! [ $? -eq 0 ]; then
+		ENABLE_TESTS=0
+		echo "configure: warning: tests are disabled because perl couldn't be found" >&2
+	fi
 fi
 
 ###################################################################
@@ -414,8 +436,6 @@ sed \
 	-e "s|@LIBCURL_LIBS@|$LIBCURL_LIBS|g" \
 	-e "s|@LIBCRYPTO_CFLAGS@|$LIBCRYPTO_CFLAGS|g" \
 	-e "s|@LIBCRYPTO_LIBS@|$LIBCRYPTO_LIBS|g" \
-	-e "s|@LIBATFC_CFLAGS@|$LIBATFC_CFLAGS|g" \
-	-e "s|@LIBATFC_LIBS@|$LIBATFC_LIBS|g" \
 	-e "s|@LIBEDIT_FOUND@|$LIBEDIT_FOUND|g" \
 	-e "s|@LIBEDIT_CFLAGS@|$LIBEDIT_CFLAGS|g" \
 	-e "s|@LIBEDIT_LIBS@|$LIBEDIT_LIBS|g" \
@@ -444,11 +464,13 @@ sed \
 	-e "s|@ENV_CPPFLAGS_FOR_BUILD@|$CPPFLAGS_FOR_BUILD|g" \
 	-e "s|@ENV_PKG_CONFIG@|$PKG_CONFIG|g" \
 	-e "s|@ENV_PKG_CONFIG_PATH@|$PKG_CONFIG_PATH|g" \
+	-e "s|@ENV_PKG_CONFIG_LIBDIR@|$PKG_CONFIG_LIBDIR|g" \
+	-e "s|@ENV_PKG_CONFIG_SYSROOT_DIR@|$PKG_CONFIG_SYSROOT_DIR|g" \
 	-e "s|@AR@|$AR|g" \
 	-e "s|@CCACHE@|$CCACHE|g" \
 	-e "s|@RANLIB@|$RANLIB|g" \
 	-e "s|@RM@|$RM|g" \
-	-e "s|@KYUA@|$KYUA|g" \
+	-e "s|@PERL@|$PERL|g" \
 	-e "s|@INSTALL@|$INSTALL|g" \
 	-e "s|@SHELL@|$SHELL|g" \
 	-e "s|@PREFIX@|$PREFIX|g" \
@@ -464,6 +486,8 @@ sed \
 	-e "s|@OBJEXT_FOR_BUILD@|$OBJEXT_FOR_BUILD|g" \
 	-e "s|@LIBEXT_FOR_BUILD@|$LIBEXT_FOR_BUILD|g" \
 	-e "s|@ENABLE_MAINTAINER@|$ENABLE_MAINTAINER|g" \
+	-e "s|@ENABLE_TESTS@|$ENABLE_TESTS|g" \
+	-e "s|@ENABLE_SANITISERS@|$ENABLE_SANITISERS|g" \
 	-e "s|@LOWDOWN@|$LOWDOWN|g" \
 	< "${srcdir}/Makefile.in" > Makefile
 
@@ -493,8 +517,6 @@ echo "              LDFLAGS: ${LDFLAGS}"
 echo "    LDFLAGS_FOR_BUILD: ${LDFLAGS_FOR_BUILD}"
 echo "       LIBCURL_CFLAGS: ${LIBCURL_CFLAGS}"
 echo "         LIBCURL_LIBS: ${LIBCURL_LIBS}"
-echo "       LIBATFC_CFLAGS: ${LIBATFC_CFLAGS}"
-echo "         LIBATFC_LIBS: ${LIBATFC_LIBS}"
 if [ $LIBEDIT_FOUND -eq 1 ]; then
 echo " Using libedit:"
 echo "       LIBEDIT_CFLAGS: ${LIBEDIT_CFLAGS}"
@@ -524,6 +546,12 @@ fi
 if [ $ENABLE_MAINTAINER -eq 1 ]; then
 echo ""
 echo "     WARNING: Maintainer mode is enabled!"
+fi
+if [ $ENABLE_MAINTAINER -eq 1 ] && [ "${OPTIMISE}" = "release" ]; then
+echo ""
+echo "     WARNING: --enable-maintainer and --release specified together."
+echo "              You probably don't want this for packaging."
+echo "              Drop --enable-maintainer!"
 fi
 echo ""
 echo "Configuration done. You may now run make."
