configure: move realpath(1) detection down
The detection used to fail the configure script entirely even before
outputting any help message on Solaris where realpath(1) does not
exist.

We should probably include a simple version of realpath with the
distfiles for people trying to build gcli on such a arcane system.

Signed-off-by: Nico Sonack <nsonack@herrhotzenplotz.de>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -33,12 +33,6 @@ die() {
 	exit 1
 }
 
-REALPATH=${REALPATH:-$(find_program realpath realpath grealpath)}
-[ $? -eq 0 ] || die "error: need realpath" # exit code of find_program()
-
-rel_srcdir="$(dirname ${0})"
-srcdir="$(${REALPATH} ${rel_srcdir})"
-
 tolower() {
 	tr '[:upper:]' '[:lower:]'
 }
@@ -226,6 +220,12 @@ while [ $# -gt 0 ]; do
 			;;
 	esac
 done
+
+REALPATH=${REALPATH:-$(find_program realpath realpath grealpath)}
+[ $? -eq 0 ] || die "error: need realpath" # exit code of find_program()
+
+rel_srcdir="$(dirname ${0})"
+srcdir="$(${REALPATH} ${rel_srcdir})"
 
 ###############################################################
 # COMPILERS
